config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'home#index'

  resources :scalas
  resources :fincas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/altitude.rb
class Altitude < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/finca.rb
class Finca < ApplicationRecord
  belongs_to :region,optional: true
  belongs_to :soil,optional: true
  belongs_to :variety,optional: true
  belongs_to :altitude,optional: true
  has_many :scalas
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/scala.rb
class Scala < ApplicationRecord
  belongs_to :finca
end

app/models/soil.rb
class Soil < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
end

app/models/variety.rb
class Variety < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fincas_controller.rb
class FincasController < ApplicationController
  before_action :set_finca, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /fincas
  # GET /fincas.json
  def index
    @fincas = Finca.all
  end

  # GET /fincas/1
  # GET /fincas/1.json
  def show
    @scalas = @finca.scalas.all
    @scala = Scala.new
  end

  # GET /fincas/new
  def new
    @finca = Finca.new
  end

  # GET /fincas/1/edit
  def edit
  end

  # POST /fincas
  # POST /fincas.json
  def create
    @finca = Finca.new(finca_params)

    respond_to do |format|
      if @finca.save
        format.html { redirect_to @finca, notice: 'Finca was successfully created.' }
        format.json { render :show, status: :created, location: @finca }
      else
        format.html { render :new }
        format.json { render json: @finca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fincas/1
  # PATCH/PUT /fincas/1.json
  def update
    respond_to do |format|
      if @finca.update(finca_params)
        format.html { redirect_to @finca, notice: 'Finca was successfully updated.' }
        format.json { render :show, status: :ok, location: @finca }
      else
        format.html { render :edit }
        format.json { render json: @finca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fincas/1
  # DELETE /fincas/1.json
  def destroy
    @finca.destroy
    respond_to do |format|
      format.html { redirect_to fincas_url, notice: 'Finca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finca
      @finca = Finca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finca_params
      params.require(:finca).permit(:region_id, :soil_id, :region_id, :variety_id, :altitude_id, :notes, :finca)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  	@fincas = Finca.all
  end
end

app/controllers/scalas_controller.rb
class ScalasController < ApplicationController
  before_action :set_scala, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /scalas
  # GET /scalas.json
  def index
    @scalas = Scala.all
  end

  # GET /scalas/1
  # GET /scalas/1.json
  def show
  end

  # GET /scalas/new
  def new
    @scala = Scala.new
  end

  # GET /scalas/1/edit
  def edit
  end

  # POST /scalas
  # POST /scalas.json
  def create
    @scala = Scala.new(scala_params)

    respond_to do |format|
      if @scala.save
        finca = @scala.finca
        format.html { redirect_to finca, notice: 'Scala was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @scala.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scalas/1
  # PATCH/PUT /scalas/1.json
  def update
    respond_to do |format|
      if @scala.update(scala_params)
        format.html { redirect_to @scala, notice: 'Scala was successfully updated.' }
        format.json { render :show, status: :ok, location: @scala }
      else
        format.html { render :edit }
        format.json { render json: @scala.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scalas/1
  # DELETE /scalas/1.json
  def destroy
    finca = @scala.finca
    @scala.destroy
    respond_to do |format|
      format.html { redirect_to finca, notice: 'Scala was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scala
      @scala = Scala.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scala_params
      params.require(:scala).permit(:finca_id, :harvested, :qqt, :paid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
# A simple way to show error messages for the current devise resource. If you need
# to customize this method, you can either overwrite it in your application helpers or
# copy the views to your application.
#
# This method is intended to stay simple and it is unlikely that we are going to change
# it to add more behavior or options.
def devise_error_messages!
	return "" if resource.errors.empty?
	messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
	sentence = I18n.t("errors.messages.not_saved",
	count: resource.errors.count,
	resource: resource.class.model_name.human.downcase)
	html = <<-HTML
		<div class="alert alert-danger" id="error_explanation">
		<a href="#" data-dismiss="alert" class="close">×</a>
		<ul>
			<li style="list-style-type:none;">
				<b>#{messages}</b>
			</li>
		</ul>
	</div>
	<!-- <div id="error_explanation">
	<ul>#{messages}</ul>
	</div> -->
	HTML
	html.html_safe
end
end

app/helpers/fincas_helper.rb
module FincasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scalas_helper.rb
module ScalasHelper
end

app/views/fincas/_form.html.erb
<!-- ProviderPage -->
  <div class="ProviderPage">
    <div class="container">
      <h3>Add / Edit Finca </h3>
      <hr />
              
      <%= form_for(finca) do |f| %>

        <%= render "/layouts/alerts" %>

        <div class="row">

          <div class="col-sm-4">
            <div class="form-group">
              <label for="">Finca</label>
              <%= f.text_field :finca,:class=>"form-control",:placeholder=>"Finca" %>
            </div>
          </div>
      
          <div class="col-sm-4">
            <div class="form-group">
              <label for="">Region</label>
              <%= f.select :region_id,Region.all.collect {|p| [ p.title, p.id ] }, { include_blank: "Select Region" }, {:class=>"form-control",:required=>true}  %>
            </div>
          </div>

          <div class="col-sm-4">
            <div class="form-group">
              <label for="">Variety</label>
              <%= f.select :variety_id,Variety.all.collect {|p| [ p.title, p.id ] }, { include_blank: "Select Variety" }, {:class=>"form-control",:required=>true}  %>
            </div>
          </div>
     
        </div> <!-- row -->

        <div class="row">

          <div class="col-sm-4">
            <div class="form-group">
              <label for="">Altitude</label>
              <%= f.select :altitude_id,Altitude.all.collect {|p| [ p.title, p.id ] }, { include_blank: "Select Altitude" }, {:class=>"form-control",:required=>true}  %>
            </div>
          </div>    

          <div class="col-sm-4">
            <div class="form-group">
              <label for="">Notes</label>
              <%= f.text_area :notes,:class=>"form-control",:placeholder=>"Notes" %>
            </div>
          </div>

          <div class="col-sm-4"></div>         
        </div> <!-- row -->

        <p class="mt40 text-center"><%= f.submit "Save",:class=>"btn redbtn"%></p>
      <% end %>

    </div> <!-- container -->
  </div>
<!-- ProviderPage -->

app/views/fincas/edit.html.erb
<%= render 'form', finca: @finca %>

app/views/fincas/index.html.erb
<!-- ProviderPage -->
<div class="ProviderPage">
  <div class="container">  
    <h3>Fincas</h3>

    <div class="table-responsive border0">
      <table class="table table-striped custab table-hover">
        <thead>
          <tr>
            <th>Title</th>
            <th>Region</th>
            <th>Variety</th>
            <th>Altitude</th>
            <th>Notes</th>
            
          </tr>
        </thead>
          <% @fincas.each do |finca| %>
            <tr data-link="<%= finca_path(finca) %>" class="clickable">
              <td><%= finca.finca %></td>
              <td><%= finca.region.title if finca.region %></td>
              <td><%= finca.variety.title if finca.variety %></td>
              <td><%= finca.altitude.title if finca.altitude %></td>
              <td><%= finca.notes %></td>
            </tr>
          <% end %>
      </table>
    </div>
    <br>

    <%= link_to 'New Finca', new_finca_path %>  
  </div>
</div>
<!-- ProviderPage -->
<script >
  $(document).ready(function(){
    $("tr[data-link]").click(function() {
      window.location = $(this).data("link")
    })
  })
</script>

app/views/fincas/new.html.erb
<%= render 'form', finca: @finca %>

app/views/fincas/show.html.erb
<!-- ProviderPage -->
<div class="ProviderPage">
  <div class="container">

    <%= render "/layouts/alerts" %>

    <div class="row">

      <div class="col-sm-6">
        <strong>Finca:</strong>
        <%= @finca.finca %>
      </div>

      <div class="col-sm-6">
        <strong>Variety:</strong>
        <%= @finca.variety.title if @finca.variety %>
      </div>
    </div> <!-- row -->

    <div class="row">

      <div class="col-sm-6">
        <strong>Altitude:</strong>
        <%= @finca.altitude.title if @finca.altitude%>
      </div>

      <div class="col-sm-6">
        <strong>Region:</strong>
        <%= @finca.region.title if @finca.region%>
      </div>
    </div> <!-- row -->

    <div class="row">
      <div class="col-sm-12">
        <strong>Notes:</strong>
        <%= @finca.notes %>
      </div>
    </div>
    <hr>
    <div><%= link_to "Edit Finca",edit_finca_path(@finca) %></div>

    <% if @finca.scalas.present? %>
      <div class="row">
        <hr>
        <h3>Receipts</h3>

        <div class="table-responsive border0">
          <table class="table table-striped custab table-hover">
            <thead>
              <tr>
                <th>Finca</th>
                <th>Harvested</th>
                <th>Qqt</th>
                <th>Paid</th>
                <th colspan="3"></th>
              </tr>
            </thead>
              <% @scalas.each do |scala| %>
                <tr>
                  <td><%= scala.finca.finca %></td>
                  <td><%= scala.harvested %></td>
                  <td><b>QQT </b><%= scala.qqt %></td>
                  <td><b>Q </b><%= scala.paid %></td>
                  <td><%= link_to 'Destroy', scala, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
          </table>
        </div>
        <br>
      </div>
    <% end %>

    <div class="row">
      <%= form_for(@scala) do |f| %>

        <hr />
        <h3>Add Receipt </h3>

        <%= f.hidden_field :finca_id,:value=>@finca.id %>
        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <label for="">Harvested</label><br>
              <%= f.datetime_select :harvested,:class=>"form-control", start_year: Time.now.year %>
            </div>
          </div>
      
          <div class="col-sm-4">
            <div class="form-group">
              <label for="">Quantity</label>

              <%= f.number_field :qqt,:class=>"form-control custom_field",:placeholder=>"Quantity" %>
              <span class="qqt">QQT</span>
            </div>
          </div>

          <div class="col-sm-4">
            <div class="form-group">
              <label for="">Paid</label>
              
              <%= f.text_field :paid,:class=>"form-control custom_q",:placeholder=>"Paid" %>
              <span class="q">Q</span>
            </div>
          </div>
        </div> <!-- row -->

        <p class="mt40 text-center"><%= f.submit "Save",:class=>"btn redbtn"%></p>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <% if current_user.role.title == "ADMIN" %>
    <!-- ProviderPage -->
    <div class="ProviderPage">
      <div class="container">  
        <h3>Fincas</h3>

        <div class="table-responsive border0">
          <table class="table table-striped custab table-hover">
            <thead>
              <tr>
                <th>Title</th>
                <th>Region</th>
                <th>Variety</th>
                <th>Altitude</th>
                <th>Notes</th>
                
              </tr>
            </thead>
              <% @fincas.each do |finca| %>
                <tr data-link="<%= finca_path(finca) %>" class="clickable">
                  <td><%= finca.finca %></td>
                  <td><%= finca.region.title if finca.region %></td>
                  <td><%= finca.variety.title if finca.variety %></td>
                  <td><%= finca.altitude.title if finca.altitude %></td>
                  <td><%= finca.notes %></td>
                </tr>
              <% end %>
          </table>
        </div>
        <br>

        <%= link_to 'New Finca', new_finca_path %>  
      </div>
    </div>

  <% end %>
<% end %>
<!-- ProviderPage -->
<script >
  $(document).ready(function(){
    $("tr[data-link]").click(function() {
      window.location = $(this).data("link")
    })
  })
</script>

app/views/layouts/_alerts.html.erb
<% if notice %>
	<div class="alert alert-info">
	  <button type="button" class="close" data-dismiss="alert">×</button>
	  <%= notice %>
	</div>
<% end %>
<% if alert %>
	<div class="alert alert-danger">
	  <button type="button" class="close" data-dismiss="alert">×</button>
	  <%= alert %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Volcan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default mynav">
       <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
             <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar top-bar"></span>
             <span class="icon-bar middle-bar"></span>
             <span class="icon-bar bottom-bar"></span>
             </button>
             <%= link_to root_path,:class=>"logotext" do %>
              <%= image_tag "trace360-logo.png",:width=>"100" %>
             <% end %>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <% if current_user.role.title == "ADMIN" %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">FINCA <span class="fa fa-angle-down"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Create New Finca", new_finca_path %></li>
                      <li><%= link_to 'All Fincas', fincas_path %></li> 
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">RECEIPT <span class="fa fa-angle-down"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "New Reciept", new_scala_path %></li>
                      <li><%= link_to 'All Reciepts', scalas_path %></li> 
                    </ul>
                  </li>
                <% end %>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
              <% else %>
                <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>
            	 
                
            </ul>
          </div>
          <!-- /.navbar-collapse -->
       </div>
       <!-- /.container-fluid -->
    </nav>

    <!-- Header -->
    
        <%= yield %>
      
  </body>
</html>

app/views/scalas/_form.html.erb
<!-- ProviderPage -->
  <div class="ProviderPage">
    <div class="container">
      <h3>Add Scala </h3>
      <hr />
              
      <%= form_for(scala) do |f| %>

        <%= render "/layouts/alerts" %>

        <div class="row">

          <div class="col-sm-6">
            <div class="form-group">
              <label for="">Finca</label>
              <%= f.select :finca_id,Finca.all.collect {|p| [ p.finca, p.id ] }, { include_blank: "Select Finca" }, {:class=>"form-control",:required=>true}  %>
            </div>
          </div>
      
          <div class="col-sm-6">
            <div class="form-group">
              <label for="">Harvested</label><br>
              <%= f.datetime_select :harvested,:class=>"form-control", start_year: Time.now.year %>
            </div>
          </div>
        </div>

        <div class="row">      

          <div class="col-sm-6">
            <div class="form-group">
              <label for="">Quantity</label>

              <%= f.number_field :qqt,:class=>"form-control custom_field",:placeholder=>"Quantity" %>
              <span class="qqt">QQT</span>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <label for="">Paid</label>
              
              <%= f.text_field :paid,:class=>"form-control custom_q",:placeholder=>"Paid" %>
              <span class="q">Q</span>
            </div>
          </div>
        </div> <!-- row -->

        <p class="mt40 text-center"><%= f.submit "Save",:class=>"btn redbtn"%></p>
      <% end %>

    </div> <!-- container -->
  </div>
<!-- ProviderPage -->

app/views/scalas/edit.html.erb
<h1>Editing Scala</h1>

<%= render 'form', scala: @scala %>

<%= link_to 'Show', @scala %> |
<%= link_to 'Back', scalas_path %>

app/views/scalas/index.html.erb
<!-- ProviderPage -->
<div class="ProviderPage">
  <div class="container">  
    <h3>Scalas</h3>

    <div class="table-responsive border0">
      <table class="table table-striped custab table-hover">
        <thead>
          <tr>
            <th>Finca</th>
            <th>Harvested</th>
            <th>Qqt</th>
            <th>Paid</th>
          </tr>
        </thead>

        <% @scalas.each do |scala| %>
          <tr data-link="<%= finca_path(scala.finca) %>" class="clickable">
            <td><%= scala.finca.finca %></td>
            <td><%= scala.harvested %></td>
            <td><%= scala.qqt %></td>
            <td><%= scala.paid %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <br>
    <%= link_to 'New Scala', new_scala_path %> 
  </div>
</div>
<!-- ProviderPage -->
<script >
  $(document).ready(function(){
    $("tr[data-link]").click(function() {
      window.location = $(this).data("link")
    })
  })
</script>

app/views/scalas/new.html.erb
<%= render 'form', scala: @scala %>

app/views/scalas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Finca:</strong>
  <%= @scala.finca %>
</p>

<p>
  <strong>Harvested:</strong>
  <%= @scala.harvested %>
</p>

<p>
  <strong>Qqt:</strong>
  <%= @scala.qqt %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @scala.paid %>
</p>

<%= link_to 'Edit', edit_scala_path(@scala) %> |
<%= link_to 'Back', scalas_path %>